include $(BUILD_DIR)/Header.mk

MODULE  := foundation
SRC_DIR :=
DEFINE  :=
INCLUDE := -I$(BASE_DIR)/src/include/ -I$(BASE_DIR)/src/include/foundation
LDFLAGS := 
LIBS    :=


$(call build-target, static_library)


include $(BUILD_DIR)/Footer.mk
