include $(BASE_DIR)/Header.mk

MODULE  := monkeyKing
SRC_DIR :=
DEFINE  :=
INCLUDE :=
LDFLAGS := -Wl,-rpath="build/lib"
LIBS    := -L$(LIBS_DIR) -lutils  -lfoundation -pthread -lrt


$(call build-target, executable)


include $(BASE_DIR)/Footer.mk
