include $(BASE_DIR)/Header.mk

MODULE  := 
SRC_DIR :=
DEFINE  :=
INCLUDE := -I$(BASE_DIR)/include/foundation
LDFLAGS := 
LIBS    :=


$(call build-target, shared_library)


include $(BASE_DIR)/Footer.mk
