include $(BUILD_DIR)/Header.mk

MODULE  := android_foundation_test
SRC_DIR :=
DEFINE  :=
INCLUDE := -I$(BASE_DIR)/android/include/foundation
LDFLAGS := -Wl,-rpath="out/lib"
LIBS    :=


$(call build-target, executable)


include $(BUILD_DIR)/Footer.mk
