include $(BUILD_DIR)/Header.mk

MODULE  := utils
SRC_DIR :=
DEFINE  :=
INCLUDE := -I$(BASE_DIR)/src/android/include
LDFLAGS := 
LIBS    :=


$(call build-target, static_library)


include $(BUILD_DIR)/Footer.mk
