include $(BUILD_DIR)/Header.mk

MODULE  := android_foundation
SRC_DIR :=
DEFINE  :=
INCLUDE := -I$(BASE_DIR)/android/include/foundation
LDFLAGS := 
LIBS    :=


$(call build-target, shared_library)


include $(BUILD_DIR)/Footer.mk
